#!/bin/bash

set -euo pipefail

docker volume rm -f cursor-sandbox-home
docker volume create cursor-sandbox-home

docker run --rm -it \
    --mount "type=volume,source=cursor-sandbox-home,target=/home/cursor" \
    "cursor-agent-sandbox" \
    bash -lc 'curl -LsSf https://astral.sh/uv/install.sh | sh && curl https://cursor.com/install -fsS | bash && curl -fsSL https://claude.ai/install.sh | bash'
