#!/bin/bash

docker run --rm -it \
    --mount "type=volume,source=cursor-sandbox-home,target=/home/cursor" \
    --mount "type=bind,source=.,target=/workspace" \
    -w /workspace \
    "cursor-agent-sandbox" \
    bash -lc "npx @google/gemini-cli"

printf '\033]0;\007'
